name: pherkin
on:
  - push
  - pull_request

jobs:
  job:
    runs-on: 'ubuntu-latest'

    name: pherkin
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@9c1eca9952ccc07f9ca4a2097b63df93d9d138e9
        with:
          perl-version: '5.40'

      - run: cpm install -g

      - name: Test with pherkin
        run: pherkin -l

